In [38]:
import tensorflow as tf
import numpy as np

def add_layer(inputs, input_size, output_size, Weights, activation_function=None):
    threshold = tf.Variable(tf.zeros([1, output_size]) + 0.1)
    Wx_plus_b = tf.matmul(inputs, Weights) + threshold
    if activation_function is None:
        outputs = Wx_plus_b
    else:
        outputs = activation_function(Wx_plus_b)
    return outputs

inputSize = int(input("Please input your input size:"))
hiddenSize = int(input("Please input your hidden size:"))
dataVolume = int(input("Please input your data volume:"))

Please input your input size:3
Please input your hidden size:3
Please input your data volume:3


In [39]:
#x_data = 2 * np.random.random_sample((dataVolume, inputSize)) -1
#y_data = np.random.rand() 
#xs = tf.placeholder(tf.float32, [dataVolume, inputSize])
#yc = tf.placeholder(tf.float32) 
x_data = tf.convert_to_tensor(2 * np.random.random_sample((dataVolume, inputSize)) -1, np.float32)
y_data = tf.convert_to_tensor(2 * np.random.random_sample((dataVolume, inputSize)) -1, np.float32)
WeightsX = tf.Variable(tf.random.normal([inputSize, hiddenSize]))
WeightsY = tf.Variable(tf.random.normal([hiddenSize, 1]))

print('wX:')
print(WeightsX)
print('wY:')
print(WeightsY)

wX:
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.76434284, -1.9237727 ,  1.0658817 ],
       [-0.71857756,  0.6574851 ,  1.0507333 ],
       [ 1.3165313 , -0.30170473, -0.79438394]], dtype=float32)>
wY:
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.1792617 ],
       [ 1.1059905 ],
       [ 0.20937468]], dtype=float32)>


In [40]:
#hiddenLayer = add_layer(xs, inputSize, hiddenSize, activation_function = tf.tanh)
#outputLayer = add_layer(hiddenLayer, hiddenSize, 1, activation_function = None)
#error = tf.reduce_mean(tf.reduce_sum(tf.square(yc - outputLayer), reduction_indices=[1]))
#train = tf.train.GradientDescentOptimizer(0.1).minimize(error)
#init = tf.initialize_all_variables()

#sess = tf.Session()
#sess.run(init)
# for i in range(500):
    # training
#sess.run(train, feed_dict={xs: x_data, yc: y_data})
#sess.close()
optimizer=tf.optimizers.SGD(0.1)

for i in range(500):
    with tf.GradientTape() as tape:
        hiddenLayer = add_layer(x_data, inputSize, hiddenSize, WeightsX, activation_function = tf.tanh)
        outputLayer = add_layer(hiddenLayer, hiddenSize, 1, WeightsY, activation_function = None)
        error = tf.reduce_mean(tf.reduce_sum(tf.square(y_data - outputLayer), axis=1))
    gradients = tape.gradient(error, [WeightsX, WeightsY])
    optimizer.apply_gradients(zip(gradients, [WeightsX, WeightsY]))

In [41]:
print('wX:')
print(WeightsX)
print('wY:')
print(WeightsY)

wX:
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-1.0573514 , -1.897516  ,  1.1041831 ],
       [-0.44153225,  0.34010452,  1.0275217 ],
       [ 1.0545204 , -0.01358812, -0.7420094 ]], dtype=float32)>
wY:
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.4893577 ],
       [ 0.2656052 ],
       [-0.31165978]], dtype=float32)>
